FROM ubuntu:18.04
WORKDIR /azp
COPY ./start.sh .
# To make it easier for build and release pipelines to run apt-get,
# configure apt to not require confirmation (assume the -y argument by default)
ENV DEBIAN_FRONTEND=noninteractive
# Set default locale for the environment
#ENV LC_ALL en_US.UTF-8
#ENV LANG en_US.UTF-8
#ENV LANGUAGE en_US.UTF-8
RUN apt-get update --fix-missing \
&& apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        jq \
        git \
        iputils-ping \
        libcurl4 \
        libicu60 \
        libunwind8 \
        netcat \
        libssl1.0 \
        wget \
        apt-transport-https \
        software-properties-common \
        locales \
&& dpkg-reconfigure locales \
&& locale-gen en_US.UTF-8 \
&& /usr/sbin/update-locale LANG=C.UTF-8 \
&& echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen && \
  locale-gen \
&& echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes \
&& wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb \
# Register the Microsoft repository GPG keys
&& dpkg -i packages-microsoft-prod.deb \
# Update the list of products
&& apt-get update \
# Enable the "universe" repositories
&& add-apt-repository universe \
# Install PowerShell
&& apt-get install -y powershell \
&& chmod +x start.sh

CMD ["./start.sh"]

